# Generated by Django 4.1.3 on 2022-12-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visioners", "0002_category_visioners_cat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visioners",
            options={
                "ordering": ["-time_create", "title"],
                "verbose_name": "Знаменитый визионер",
                "verbose_name_plural": "Знаменитые визионеры",
            },
        ),
        migrations.AlterField(
            model_name="visioners",
            name="photo",
            field=models.ImageField(upload_to="photos/%Y/%m/%d/"),
        ),
    ]
