# Generated by Django 4.1.3 on 2022-12-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("visioners", "0003_alter_visioners_options_alter_visioners_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Категория"
            ),
        ),
        migrations.AlterField(
            model_name="visioners",
            name="cat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="visioners.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="visioners",
            name="content",
            field=models.TextField(blank=True, verbose_name="Текст статьи"),
        ),
        migrations.AlterField(
            model_name="visioners",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Публикация"),
        ),
        migrations.AlterField(
            model_name="visioners",
            name="photo",
            field=models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Фото"),
        ),
        migrations.AlterField(
            model_name="visioners",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="visioners",
            name="time_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Время публикации"),
        ),
        migrations.AlterField(
            model_name="visioners",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
    ]
